name: Build docker image
on:
  push:
    # Publish `master` as Docker `latest` image.
    branches:
      - master

    # Publish `v1.2.3` tags as releases.
    tags:
      - v*

    # Run tests for any PRs.
    pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      build:
        runs-on: ubuntu-latest
        steps:
          - uses: actions/checkout@master
          - name: Publish to Registry
            uses: elgohr/Publish-Docker-Github-Action@master
            with:
              name: lexinek/hello-world
              username: ${{ secrets.DOCKER_HUB_USER }}
              password: ${{ secrets.DOCKER_HUB_TOKEN }}
              cache: ${{ github.event_name != 'schedule' }}
